In [2]:
import pandas as pd

In [25]:
dados = {
    'Times': ['Corinthians', 'Palmeiras', 'Grêmio', 'São Paulo', 'Vasco'],
    'Partidas_Jogadas': [10, 10, 10, 10, 10],
    'Vitorias': [7, 5, 6, 4, 3],
    'Empates': [2, 3, 1, 3, 22],
    'Derrotas': [1, 2, 3, 5, 8,],
    'Gols_Pro': [22, 18, 16, 14, 10],
    'Gols_Contra': [10, 12, 15, 16, 20]
                 
}

In [30]:
df = pd.DataFrame(dados)
df

,Times,Partidas_Jogadas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra
0,Corinthians,10,7,2,1,22,10
1,Palmeiras,10,5,3,2,18,12
2,Grêmio,10,6,1,3,16,15
3,São Paulo,10,4,3,5,14,16
4,Vasco,10,3,22,8,10,20

In [31]:
df['Saldo_Gols'] = df['Gols_Pro'] - df['Gols_Contra']
df

,Times,Partidas_Jogadas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra,Saldo_Gols
0,Corinthians,10,7,2,1,22,10,12
1,Palmeiras,10,5,3,2,18,12,6
2,Grêmio,10,6,1,3,16,15,1
3,São Paulo,10,4,3,5,14,16,-2
4,Vasco,10,3,22,8,10,20,-10

In [32]:
df['Pontos'] = df['Vitorias'] * 3 + df['Empates'] * 1 
df

,Times,Partidas_Jogadas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra,Saldo_Gols,Pontos
0,Corinthians,10,7,2,1,22,10,12,23
1,Palmeiras,10,5,3,2,18,12,6,18
2,Grêmio,10,6,1,3,16,15,1,19
3,São Paulo,10,4,3,5,14,16,-2,15
4,Vasco,10,3,22,8,10,20,-10,31

In [33]:
df = df.sort_values(by='Pontos', ascending=False)
df

,Times,Partidas_Jogadas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra,Saldo_Gols,Pontos
4,Vasco,10,3,22,8,10,20,-10,31
0,Corinthians,10,7,2,1,22,10,12,23
2,Grêmio,10,6,1,3,16,15,1,19
1,Palmeiras,10,5,3,2,18,12,6,18
3,São Paulo,10,4,3,5,14,16,-2,15

In [34]:
df.to_excel('D:/Area de trabalho/Data-Science-Learning/02-Python/Base-de-dados/campeonato_futebol.xlsx')