#  Pandas — Pivot & Transformação
> Estudo prático com `pivot_table`, `melt`, `stack/unstack`, `crosstab` e `transform`
**Tema:** Reshaping e agregação de dados com Pandas  
**Notebook:** `pandas_pivot_transformacao.ipynb`

In [1]:
import pandas as pd
import numpy as numpy

In [ ]:
# Dicionário com dados fictícios de vendas: vendedor, região, produto, trimestre, vendas, meta e unidades

dados = {
    "vendedor":   ["Ana", "Bruno", "Ana", "Carlos", "Bruno", "Carlos", "Ana", "Bruno", "Carlos", "Ana"],
    "regiao":     ["Sul", "Norte", "Norte", "Sul", "Sul", "Norte", "Leste", "Leste", "Leste", "Sul"],
    "produto":    ["Notebook", "Tablet", "Notebook", "Tablet", "Smartphone", "Notebook", "Tablet", "Notebook", "Smartphone", "Smartphone"],
    "trimestre":  ["Q1", "Q1", "Q2", "Q1", "Q2", "Q2", "Q1", "Q2", "Q1", "Q2"],
    "vendas":     [12000, 8500, 15000, 9300, 11200, 7800, 6400, 13000, 10500, 9800],
    "meta":       [10000, 9000, 13000, 8000, 10000, 8000, 7000, 12000, 9000, 9000],
    "unidades":   [4, 17, 5, 18, 8, 6, 13, 4, 7, 3]
}

In [3]:
df = pd.DataFrame(dados)

In [5]:
df.head(10)

  vendedor regiao     produto trimestre  vendas   meta  unidades
0      Ana    Sul    Notebook        Q1   12000  10000         4
1    Bruno  Norte      Tablet        Q1    8500   9000        17
2      Ana  Norte    Notebook        Q2   15000  13000         5
3   Carlos    Sul      Tablet        Q1    9300   8000        18
4    Bruno    Sul  Smartphone        Q2   11200  10000         8
5   Carlos  Norte    Notebook        Q2    7800   8000         6
6      Ana  Leste      Tablet        Q1    6400   7000        13
7    Bruno  Leste    Notebook        Q2   13000  12000         4
8   Carlos  Leste  Smartphone        Q1   10500   9000         7
9      Ana    Sul  Smartphone        Q2    9800   9000         3

In [ ]:
# Pivot table:  vendas por vendedor e trimestre

pivot_df = df.pivot_table(index="vendedor", columns="trimestre", values="vendas", aggfunc="sum")
pivot_df

trimestre     Q1     Q2
vendedor
Ana        18400  24800
Bruno       8500  24200
Carlos     19800   7800

In [17]:
# Pivot table: total de vendas por vendedor

pivot_total_venda = df.pivot_table(index="vendedor", columns="trimestre", values="vendas", aggfunc="sum", margins=True, margins_name="Total")
pivot_total_venda

trimestre     Q1     Q2   Total
vendedor
Ana        18400  24800   43200
Bruno       8500  24200   32700
Carlos     19800   7800   27600
Total      46700  56800  103500

In [18]:
# Pivot table: Multiplas funções de agregação

multi_pivot = df.pivot_table(index="vendedor", columns="trimestre", values="vendas", aggfunc=["sum", "mean", "max"])
multi_pivot

             sum           mean             max
trimestre     Q1     Q2      Q1       Q2     Q1     Q2
vendedor
Ana        18400  24800  9200.0  12400.0  12000  15000
Bruno       8500  24200  8500.0  12100.0   8500  13000
Carlos     19800   7800  9900.0   7800.0  10500   7800