#  Pandas — Pivot & Transformação
> Estudo prático com `pivot_table`, `melt`, `stack/unstack`, `crosstab` e `transform`
**Tema:** Reshaping e agregação de dados com Pandas  
**Notebook:** `pandas_pivot_transformacao.ipynb`

In [1]:
import pandas as pd
import numpy as numpy

In [ ]:
# Dicionário com dados fictícios de vendas: vendedor, região, produto, trimestre, vendas, meta e unidades

dados = {
    "vendedor":   ["Ana", "Bruno", "Ana", "Carlos", "Bruno", "Carlos", "Ana", "Bruno", "Carlos", "Ana"],
    "regiao":     ["Sul", "Norte", "Norte", "Sul", "Sul", "Norte", "Leste", "Leste", "Leste", "Sul"],
    "produto":    ["Notebook", "Tablet", "Notebook", "Tablet", "Smartphone", "Notebook", "Tablet", "Notebook", "Smartphone", "Smartphone"],
    "trimestre":  ["Q1", "Q1", "Q2", "Q1", "Q2", "Q2", "Q1", "Q2", "Q1", "Q2"],
    "vendas":     [12000, 8500, 15000, 9300, 11200, 7800, 6400, 13000, 10500, 9800],
    "meta":       [10000, 9000, 13000, 8000, 10000, 8000, 7000, 12000, 9000, 9000],
    "unidades":   [4, 17, 5, 18, 8, 6, 13, 4, 7, 3]
}

In [3]:
df = pd.DataFrame(dados)

In [5]:
df.head(10)

  vendedor regiao     produto trimestre  vendas   meta  unidades
0      Ana    Sul    Notebook        Q1   12000  10000         4
1    Bruno  Norte      Tablet        Q1    8500   9000        17
2      Ana  Norte    Notebook        Q2   15000  13000         5
3   Carlos    Sul      Tablet        Q1    9300   8000        18
4    Bruno    Sul  Smartphone        Q2   11200  10000         8
5   Carlos  Norte    Notebook        Q2    7800   8000         6
6      Ana  Leste      Tablet        Q1    6400   7000        13
7    Bruno  Leste    Notebook        Q2   13000  12000         4
8   Carlos  Leste  Smartphone        Q1   10500   9000         7
9      Ana    Sul  Smartphone        Q2    9800   9000         3

In [ ]:
# Pivot table:  vendas por vendedor e trimestre

pivot_df = df.pivot_table(index="vendedor", columns="trimestre", values="vendas", aggfunc="sum")
pivot_df

trimestre     Q1     Q2
vendedor
Ana        18400  24800
Bruno       8500  24200
Carlos     19800   7800

In [20]:
# Pivot table: total de vendas por vendedor

pivot_total_venda = df.pivot_table(index="vendedor", columns="trimestre", values="vendas", aggfunc="sum", margins=True, margins_name="Total")
pivot_total_venda

trimestre     Q1     Q2   Total
vendedor
Ana        18400  24800   43200
Bruno       8500  24200   32700
Carlos     19800   7800   27600
Total      46700  56800  103500

In [23]:
# Pivot table: Multiplas funções de agregação

multi_pivot = df.pivot_table(index="vendedor", columns="produto",values="vendas", aggfunc=["sum", "mean", "max","min"])
multi_pivot

              sum                       mean                         max  \
produto  Notebook Smartphone Tablet Notebook Smartphone  Tablet Notebook
vendedor
Ana         27000       9800   6400  13500.0     9800.0  6400.0    15000
Bruno       13000      11200   8500  13000.0    11200.0  8500.0    13000
Carlos       7800      10500   9300   7800.0    10500.0  9300.0     7800

                                min
produto  Smartphone Tablet Notebook Smartphone Tablet
vendedor
Ana            9800   6400    12000       9800   6400
Bruno         11200   8500    13000      11200   8500
Carlos        10500   9300     7800      10500   9300

In [24]:
# Dicionário expandido: mais vendedores, produtos, trimestres e com coluna de cidade
dados2 = {
    "vendedor":  [
        "Ana", "Bruno", "Carlos", "Diana", "Eduardo",
        "Ana", "Bruno", "Carlos", "Diana", "Eduardo",
        "Ana", "Bruno", "Carlos", "Diana", "Eduardo",
        "Ana", "Bruno", "Carlos", "Diana", "Eduardo"
    ],
    "cidade": [
        "São Paulo", "Curitiba", "Belo Horizonte", "Porto Alegre", "Recife",
        "São Paulo", "Curitiba", "Belo Horizonte", "Porto Alegre", "Recife",
        "São Paulo", "Curitiba", "Belo Horizonte", "Porto Alegre", "Recife",
        "São Paulo", "Curitiba", "Belo Horizonte", "Porto Alegre", "Recife"
    ],
    "regiao": [
        "Sudeste", "Sul", "Sudeste", "Sul", "Nordeste",
        "Sudeste", "Sul", "Sudeste", "Sul", "Nordeste",
        "Sudeste", "Sul", "Sudeste", "Sul", "Nordeste",
        "Sudeste", "Sul", "Sudeste", "Sul", "Nordeste"
    ],
    "produto": [
        "Notebook", "Tablet", "Smartphone", "Monitor", "Teclado",
        "Headset", "Notebook", "Monitor", "Smartphone", "Tablet",
        "Teclado", "Headset", "Notebook", "Tablet", "Monitor",
        "Smartphone", "Teclado", "Headset", "Monitor", "Notebook"
    ],
    "trimestre": [
        "Q1", "Q1", "Q1", "Q1", "Q1",
        "Q2", "Q2", "Q2", "Q2", "Q2",
        "Q3", "Q3", "Q3", "Q3", "Q3",
        "Q4", "Q4", "Q4", "Q4", "Q4"
    ],
    "vendas": [
        14000, 8700, 11500, 9200, 4300,
        16000, 9100, 13200, 10800, 5100,
        18500, 7800, 15000, 11400, 6200,
        21000, 8300, 17500, 13000, 7400
    ],
    "meta": [
        13000, 9000, 10000, 8500, 4000,
        15000, 9500, 12000, 10000, 5000,
        17000, 8000, 14000, 11000, 6000,
        20000, 8000, 16000, 12000, 7000
    ],
    "unidades": [
        5, 18, 9, 4, 22,
        6, 19, 5, 8, 25,
        7, 16, 6, 9, 21,
        8, 17, 7, 11, 28
    ]
}

In [25]:
df = pd.DataFrame(dados2)
df.head(10)

,vendedor,cidade,regiao,produto,trimestre,vendas,meta,unidades
0,Ana,São Paulo,Sudeste,Notebook,Q1,14000,13000,5
1,Bruno,Curitiba,Sul,Tablet,Q1,8700,9000,18
2,Carlos,Belo Horizonte,Sudeste,Smartphone,Q1,11500,10000,9
3,Diana,Porto Alegre,Sul,Monitor,Q1,9200,8500,4
4,Eduardo,Recife,Nordeste,Teclado,Q1,4300,4000,22
5,Ana,São Paulo,Sudeste,Headset,Q2,16000,15000,6
6,Bruno,Curitiba,Sul,Notebook,Q2,9100,9500,19
7,Carlos,Belo Horizonte,Sudeste,Monitor,Q2,13200,12000,5
8,Diana,Porto Alegre,Sul,Smartphone,Q2,10800,10000,8
9,Eduardo,Recife,Nordeste,Tablet,Q2,5100,5000,25

In [40]:
multi_pivot_vendas = df.pivot_table(index=["vendedor", "cidade"],
                                    columns=["produto",],
                                    values="vendas",
                                    aggfunc="sum",      
                                    margins=True, margins_name="Total Vendas"
                                
                                                                         
                                    )

multi_pivot_vendas

,produto,Headset,Monitor,Notebook,Smartphone,Tablet,Teclado,Total Vendas
vendedor,cidade,,,,,,,
Ana,São Paulo,16000.0,NaN,14000.0,21000.0,NaN,18500.0,69500
Bruno,Curitiba,7800.0,NaN,9100.0,NaN,8700.0,8300.0,33900
Carlos,Belo Horizonte,17500.0,13200.0,15000.0,11500.0,NaN,NaN,57200
Diana,Porto Alegre,NaN,22200.0,NaN,10800.0,11400.0,NaN,44400
Eduardo,Recife,NaN,6200.0,7400.0,NaN,5100.0,4300.0,23000
Total Vendas,,41300.0,41600.0,45500.0,43300.0,25200.0,31100.0,228000

In [45]:
multi_pivot_vendas = df.pivot_table(
    index=["vendedor", "cidade"],
    columns=["produto"],
    values=["vendas", "meta"],
    aggfunc="sum",
    fill_value=0,
    margins=True,
    margins_name="Total Vendas"
)

multi_pivot_vendas

                               meta                                     \
produto                     Headset Monitor Notebook Smartphone Tablet
vendedor     cidade
Ana          São Paulo        15000       0    13000      20000      0
Bruno        Curitiba          8000       0     9500          0   9000
Carlos       Belo Horizonte   16000   12000    14000      10000      0
Diana        Porto Alegre         0   20500        0      10000  11000
Eduardo      Recife               0    6000     7000          0   5000
Total Vendas                  39000   38500    43500      40000  25000

                                                  vendas                   \
produto                     Teclado Total Vendas Headset Monitor Notebook
vendedor     cidade
Ana          São Paulo        17000        65000   16000       0    14000
Bruno        Curitiba          8000        34500    7800       0     9100
Carlos       Belo Horizonte       0        52000   17500   13200    15000
Diana        Porto Alegre         0        41500       0   22200        0
Eduardo      Recife            4000        22000       0    6200     7400
Total Vendas                  29000       215000   41300   41600    45500


produto                     Smartphone Tablet Teclado Total Vendas
vendedor     cidade
Ana          São Paulo           21000      0   18500        69500
Bruno        Curitiba                0   8700    8300        33900
Carlos       Belo Horizonte      11500      0       0        57200
Diana        Porto Alegre        10800  11400       0        44400
Eduardo      Recife                  0   5100    4300        23000
Total Vendas                     43300  25200   31100       228000

In [ ]:
# pd.crosstab cria uma tabela de frequência cruzada entre duas variáveis categóricas.

pd.crosstab(
    df["vendedor"],
    df["produto"],
    values=df["vendas"],
    aggfunc="sum"
).fillna(0)

produto   Headset  Monitor  Notebook  Smartphone   Tablet  Teclado
vendedor
Ana       16000.0      0.0   14000.0     21000.0      0.0  18500.0
Bruno      7800.0      0.0    9100.0         0.0   8700.0   8300.0
Carlos    17500.0  13200.0   15000.0     11500.0      0.0      0.0
Diana         0.0  22200.0       0.0     10800.0  11400.0      0.0
Eduardo       0.0   6200.0    7400.0         0.0   5100.0   4300.0

In [66]:
# stack() — colunas de produto viram linhas
pivot_df.stack()
# resultado: cada (vendedor, produto) vira uma linha separada

# unstack() — índice interno (cidade) vira coluna
pivot_df.unstack()
# resultado: cidade sai do índice e vira coluna

trimestre  vendedor
Q1         Ana         18400
           Bruno        8500
           Carlos      19800
Q2         Ana         24800
           Bruno       24200
           Carlos       7800
dtype: int64

In [75]:
# total de vendas do vendedor repetido em cada linha dele
df["total_vendedor"] = df.groupby("vendedor")["vendas"].transform("sum")

# média de vendas do grupo em cada linha
df["media_vendedor"] = df.groupby("vendedor")["vendas"].transform("mean")

# % que cada venda representa dentro do vendedor
df["pct_vendedor"] = df["vendas"] / df.groupby("vendedor")["vendas"].transform("sum") * 100
df.head(10)

,vendedor,cidade,regiao,produto,trimestre,vendas,meta,unidades,faixa,quartil,media_vendedor,pct_vendedor,total_vendedor
0,Ana,São Paulo,Sudeste,Notebook,Q1,14000,13000,5,alto,Q3,17375.0,20.143885,69500
1,Bruno,Curitiba,Sul,Tablet,Q1,8700,9000,18,médio,Q2,8475.0,25.663717,33900
2,Carlos,Belo Horizonte,Sudeste,Smartphone,Q1,11500,10000,9,médio,Q3,14300.0,20.104895,57200
3,Diana,Porto Alegre,Sul,Monitor,Q1,9200,8500,4,médio,Q2,11100.0,20.720721,44400
4,Eduardo,Recife,Nordeste,Teclado,Q1,4300,4000,22,baixo,Q1,5750.0,18.695652,23000
5,Ana,São Paulo,Sudeste,Headset,Q2,16000,15000,6,alto,Q4,17375.0,23.021583,69500
6,Bruno,Curitiba,Sul,Notebook,Q2,9100,9500,19,médio,Q2,8475.0,26.843658,33900
7,Carlos,Belo Horizonte,Sudeste,Monitor,Q2,13200,12000,5,alto,Q3,14300.0,23.076923,57200
8,Diana,Porto Alegre,Sul,Smartphone,Q2,10800,10000,8,médio,Q2,11100.0,24.324324,44400
9,Eduardo,Recife,Nordeste,Tablet,Q2,5100,5000,25,baixo,Q1,5750.0,22.173913,23000